name       : psutils
version    : '1.23'
release    : 1
source     :
    - https://github.com/rrthomas/psutils/archive/v1.23.tar.gz : b7db52e30c763bb1ca3e073a8b1648728899157e10aedc0e0fcc97e19ea72279
license    : psutils
component  : programming.tools
networking : yes
summary    : Utilities for manipulating PostScript documents
description: |
    PSUtils is a suite of utilities for manipulating PostScript documents produced according to the Document Structuring Conventions. It is possible to select and rearrange pages, including arrangement into signatures for booklet printing, and page merging for n-up printing.
builddeps  :
    - ghostscript-devel
    - git
setup      : |
    %patch -p1 < $pkgfiles/patch-30-unsigned.patch
    ./bootstrap
    %reconfigure
build      : |
    %make
install    : |
    %make_install
