name       : psutils
version    : '2.5'
release    : 4
source     :
    - https://github.com/rrthomas/psutils/releases/download/v2.05/psutils-2.05.tar.gz : 1ab103210baf139789f9e049165088d08ad041fb9f28d4bdc2430e5773b63346
license    : psutils
component  : programming.tools
networking : yes
summary    : Utilities for manipulating PostScript documents
description: |
    PSUtils is a suite of utilities for manipulating PostScript documents produced according to the Document Structuring Conventions. It is possible to select and rearrange pages, including arrangement into signatures for booklet printing, and page merging for n-up printing.
builddeps  :
    - ghostscript-devel
setup      : |
    %patch -p1 < $pkgfiles/perl-vendorlib-make.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
