name       : psutils
version    : 1.90
release    : 2
source     :
    - https://github.com/rrthomas/psutils/archive/v1.90.tar.gz : b45a78b14fa213f8705a0347f7429272bf6cb7c0367f7408915aaf66d0734a9b
license    : psutils
component  : programming.tools
networking : yes
summary    : Utilities for manipulating PostScript documents
description: |
    PSUtils is a suite of utilities for manipulating PostScript documents produced according to the Document Structuring Conventions. It is possible to select and rearrange pages, including arrangement into signatures for booklet printing, and page merging for n-up printing.
builddeps  :
    - ghostscript-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
